services:
  Pokedex.Users.UserRepository:
    class: ../repositories/InMemoryUserRepository
    arguments: []

  Pokedex.Users.FavoritePokemonCreator:
    class: ../../domain/FavoritePokemonCreator
    arguments: ['@Pokedex.Users.UserRepository']

  Pokedex.Users.UserFinder:
    class: ../../domain/UserFinder
    arguments: ['@Pokedex.Users.UserRepository']

  Pokedex.Users.UserCreator:
    class: ../../domain/UserCreator
    arguments: ['@Pokedex.Users.UserRepository']

  Pokedex.Users.AddFavoritePokemonToUser:
    class: ../../application/AddFavoritePokemonToUser
    arguments: ['@Pokedex.Users.UserFinder', '@Pokedex.Users.FavoritePokemonCreator']

  Pokedex.Users.CreateUser:
    class: ../../application/CreateUser
    arguments: ['@Pokedex.Users.UserCreator']
